services:
  lucos_scheduled_scripts:
    build: base-image
    image: lucas42/lucos_scheduled_scripts
    container_name: lucos_scheduled_scripts
  test:
    build: test
    image: lucas42/lucos_scheduled_scripts_test
    container_name: lucos_scheduled_scripts_test
    environment:
      - SYSTEM
      - LOGANNE_ENDPOINT
      - SCHEDULE_TRACKER_ENDPOINT